name: Deploy 15-ML Streamlit App to Azure Container Apps via Docker Hub

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HF_API_KEY: ${{ secrets.HF_API_KEY }}  # HuggingFace API key
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
      RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      CONTAINER_APP_NAME: ${{ secrets.CONTAINER_APP_NAME }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      IMAGE_NAME: ml-15-app

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Build Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure subscription
      run: az account set --subscription $AZURE_SUBSCRIPTION

    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name $CONTAINER_APP_NAME \
          --resource-group $RESOURCE_GROUP \
          --image $DOCKERHUB_USERNAME/$IMAGE_NAME:latest \
          --cpu 1 --memory 1.5Gi \
          --set-env-vars HF_API_KEY=${HF_API_KEY}

    - name: Deployment Complete
      run: echo "✅ Deployment finished! Your 15-ML Streamlit app is live in Azure Container App."
